### ISSUE TITLE
Kirale DFU Version does not match Downloads

### ISSUE THREAD

**Issue by JUDOKICK** [KiraleTech/KiBRA#3]
Current version in kibra/__init__.py doesn't match the DFU that is publicly available on the the kirale.com/support#downloads site. 

Suggested fix.

Match the version from 1.3.... to current version 1.2.7274.47206

**Comment by KiraleDev** [comment]
@JUDOKICK the Thread 1.2 KiNOS release (1.3.7321 currently) is still under development since the Thread 1.2 Certification Program is not finished yet. That's the reason it's not in our [Downloads section](https://www.kirale.com/support/#downloads) yet, but we might publish it as a beta version.

In any case, the provided [Armbian image](https://www.kirale.com/products/ktbrn1/#resources) comes with KiNOS 1.3.7321 included and automatically flashes the attached KTWM102 NCP of the KRBRN1 if it's version doesn't match.

**Comment by JUDOKICK** [comment]
Ah I see. This would be true if I was using the KRBRN1 but I have it installed on a RaspberryPi.

**Comment by KiraleDev** [comment]
By the way, as long as you don't enable the DUA flag for the announced prefix most of the Border Router functionalities will be working with the KiNOS Thread v1.1 firmware.

**Comment by KiraleDev** [comment]
@JUDOKICK the _KiNOS Thread NCP v1.3.7321 (Beta)_ DFU is available now in the [KTDG102](https://www.kirale.com/products/ktdg102/#resources) page.
