### ISSUE TITLE
db/leases not found

### ISSUE THREAD

**Issue by JUDOKICK** [KiraleTech/KiBRA#4]
When accessing the webserver from the browser. Browser reports back that db/leases is not found. It is not loaded in sources either. What is required to make it acessible ?

**Comment by KiraleDev** [comment]
@JUDOKICK in which system are you running KiBRA? Have you installed all the dependencies?

**Comment by JUDOKICK** [comment]
Its running on a RaspberryPi and yes all dependencies have been installed. Although I can't say I'm sure because the list for deps isn't posted.

**Comment by KiraleDev** [comment]
This is the list of required packages: https://github.com/KiraleTech/KiBRA#requirements

In any case the error you mention is likely due to the DHCP server not being enabled. This can be done by adding these lines in `/opt/kirale/kibra.cfg`:

```
{
  "autostart": "1",
  "prefix_dhcp": "1"
}
```

 And forcing a KiBRA restart after:
`service kibra restart`

**Comment by JUDOKICK** [comment]
Thanks. Gave this a go and it started running!
